x-logging: &default-logging
    options:
        max-size: '20k'
        max-file: '10'

services:
    django:
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        command: gunicorn asgi:application -k restartable_uvicorn.RestartableUvicornWorker -b :8000 -b :80 --reload
        # environment:
        #   # To make things play nice with dj-database-url
        #   - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
        env_file: .env
        volumes:
            - ./src/backend:/app
        ports:
            - 8000:8000
            - 80:80
            - 8001:8001

        stdin_open: true
        tty: true
        logging: *default-logging

    redis:
        image: redis
        ports:
            - 6379:6379
        logging:
            options:
                max-size: '20k'
                max-file: '10'

volumes:
    myapp:
