# Generated by Django 5.1.4 on 2025-01-02 01:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0002_subwayline_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwayline',
            name='delay_start_time',
        ),
        migrations.AddField(
            model_name='subwayline',
            name='status_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subwayline',
            name='total_normal_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('delayed', 'Delayed')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.subwayline')),
            ],
            options={
                'indexes': [models.Index(fields=['line', 'status', 'start_time'], name='subway_stat_line_id_99e205_idx')],
            },
        ),
    ]
