# Generated by Django 5.1.4 on 2025-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0003_remove_subwayline_delay_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statushistory',
            name='subway_stat_line_id_99e205_idx',
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['line_id'], name='subway_stat_line_id_5ebeee_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['line', 'status'], name='subway_stat_line_id_bef677_idx'),
        ),
    ]
